Repository unabridged/motion, pull requests merged in 2020-07, with the labels that each got.

#11 Allowlist properties to be copied from event instead of checking type
  javascript/serializeEvent.js
Labels: bug

#10 Allow TEXTAREAs to be updated
  javascript/reconcile.js
Labels: bug

#13 Use click as default event for input[type=submit]
  javascript/BindingManager.js
  javascript/parseBindings.js
  spec/javascript/parseBindings.js
Labels: bug

#9 Periodic timers ⏰
  README.md
  lib/motion/action_cable_extentions.rb
  lib/motion/action_cable_extentions/declarative_notifications.rb
  lib/motion/action_cable_extentions/declarative_streams.rb
  lib/motion/action_cable_extentions/synchronization.rb
  lib/motion/channel.rb
  lib/motion/component.rb
  lib/motion/component/broadcasts.rb
  lib/motion/component/motions.rb
  lib/motion/component/periodic_timers.rb
  lib/motion/component_connection.rb
  spec/motion/channel_spec.rb
  spec/motion/component/broadcasts_spec.rb
  spec/motion/component/motions_spec.rb
  spec/motion/component/periodic_timers_spec.rb
  spec/motion/component_connection_spec.rb
  spec/motion/component_spec.rb
  spec/spec_helper.rb
  spec/support/test_application.rb
  spec/support/test_application/app/components/timer_component.rb
  spec/support/test_application/app/controllers/timer_components_controller.rb
  spec/support/test_application/config/routes.rb
  spec/support/test_component.rb
  spec/system/core_functionality_spec.rb
Labels: enhancement

#16 Add support for accessing the currentTarget
  README.md
  javascript/serializeEvent.js
  lib/motion/event.rb
  spec/motion/event_spec.rb
Labels: enhancement

#17 Replace nested components when outer state changes
  javascript/AttributeTracker.js
  javascript/BindingManager.js
  javascript/Client.js
  javascript/Component.js
Labels: bug

#18 Less wasteful render_hash
  lib/motion/component/rendering.rb
  lib/motion/serializer.rb
  spec/motion/serializer_spec.rb
Labels: enhancement

#15 fix render? in component
  javascript/reconcile.js
  lib/motion/markup_transformer.rb
  spec/motion/markup_transformer_spec.rb
Labels: bug

#12 Add revision class to calculate revision hash
  lib/generators/motion/templates/motion.rb
  lib/motion.rb
  lib/motion/configuration.rb
  lib/motion/errors.rb
  lib/motion/revision_calculator.rb
  spec/motion/configuration_spec.rb
  spec/motion/revision_calculator_spec.rb
  spec/spec_helper.rb
Labels: enhancement

#25 Support periodic timers outside of test environment 😬
  lib/motion/action_cable_extentions/declarative_notifications.rb
Labels: bug

#26 Markup transformer cleanup
  lib/motion/markup_transformer.rb
  spec/motion/markup_transformer_spec.rb
Labels: bug

#23 Don't `preventDefault` when the component is not connected
  javascript/AttributeTracker.js
  javascript/BindingManager.js
  javascript/Client.js
  javascript/Component.js
  javascript/serializeEvent.js
  lib/generators/motion/templates/motion.js
Labels: documentation, enhancement

#24 Support Warden (and Devise) out of the box
  lib/generators/motion/templates/motion.rb
  lib/motion/configuration.rb
Labels: enhancement

#28 Reformat and cleanup error messages
  lib/motion/component/lifecycle.rb
  lib/motion/errors.rb
  spec/motion/component/lifecycle_spec.rb
Labels: enhancement

#27 Callbacks for actions and connection
  lib/motion/component/broadcasts.rb
  lib/motion/component/lifecycle.rb
  lib/motion/component/motions.rb
  lib/motion/component/periodic_timers.rb
  lib/motion/component/rendering.rb
  lib/motion/component_connection.rb
  lib/motion/errors.rb
  spec/motion/channel_spec.rb
  spec/motion/component/broadcasts_spec.rb
  spec/motion/component/lifecycle_spec.rb
  spec/motion/component/motions_spec.rb
  spec/motion/component/periodic_timers_spec.rb
  spec/motion/component/rendering_spec.rb
  spec/motion/component_connection_spec.rb
  spec/support/test_component.rb
Labels: enhancement

#31 Add `error_notification_proc` configuration option
  lib/generators/motion/templates/motion.rb
  lib/motion.rb
  lib/motion/configuration.rb
  lib/motion/log_helper.rb
  spec/motion/log_helper_spec.rb
  spec/motion_spec.rb
Labels: enhancement

#32 More ergonomic callbacks (`bind`)
  lib/motion.rb
  lib/motion/callback.rb
  lib/motion/channel.rb
  lib/motion/component.rb
  lib/motion/component/callbacks.rb
  lib/motion/component/rendering.rb
  spec/motion/callback_spec.rb
  spec/motion/component/callbacks_spec.rb
  spec/motion/component_spec.rb
  spec/support/test_application/app/components/button_component.html.erb
  spec/support/test_application/app/components/button_component.rb
  spec/support/test_application/app/components/callback_component.html.erb
  spec/support/test_application/app/components/callback_component.rb
  spec/support/test_application/app/controllers/callback_components_controller.rb
  spec/support/test_application/config/routes.rb
  spec/system/core_functionality_spec.rb
Labels: enhancement

#38 Add compression to the serialization pipeline.
  Gemfile.lock
  gemfiles/rails_5_2.gemfile.lock
  gemfiles/rails_6_0.gemfile.lock
  gemfiles/rails_master.gemfile.lock
  lib/motion/serializer.rb
  motion.gemspec
Labels: enhancement

#35 Refactor BindingManager to avoid DOM API
  javascript/BindingManager.js
Labels: enhancement

#40 Add callback example to the readme
  README.md
Labels: documentation
